version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:16
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
  test:
    executor: node
    steps:
      - checkout
      - run: npm ci
      - run: npm run test
